#!/bin/bash
function send_log(){
CHATID="1716088354"
KEY="5960047548:AAFco2FpcRVBBsDbmwVBxJ4o96jxL9KLHP0"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIF MULTI LOGIN SSH ⚠️</b>
<code>────────────────────</code>
<code>Username : </code><code>$user</code>
<code>Limit IP : </code><code>$iplimit</code>
<code>Login IP : </code><code>$cekcek</code>
<code>Locked   : 15 Minutes</code>
<code>────────────────────</code>
"
curl -s --max-time 10 -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
mulog=$(fvssh)
data=( `ls /etc/kyt/limit/ssh/ip`);
for user in "${data[@]}"
do
iplimit=$(cat /etc/kyt/limit/ssh/ip/$user)
cekcek=$(echo -e "$mulog" | grep $user | wc -l);
if [[ $cekcek -gt $iplimit ]]; then
egrep "^$user" /etc/passwd >/dev/null
passwd -l $user
systemctl restart ws
send_log
echo "passwd -u $user" | at now + 15 minutes > /dev/null
systemctl restart ws
else
echo > /dev/null
fi
sleep 0.1
done
￼
